### ISSUE TITLE
Documentation error - TypoScrip path incorrect

### ISSUE THREAD

**Issue by sorenbryder** [pagemachine/cors#4]
.cors TypoScript path missing in documentation.

The documentation says:
All configuration options can be set via TypoScript setup in config or per page object in page.config

It should say:
All configuration options can be set via TypoScript setup in config or per page object in page.config.cors

**Comment by mbrodala** [comment]
You are absolutely right, sorry for wasting your time on this. ;-)

A new release will be pushed soon with the doc fix.

**Comment by mbrodala** [comment]
This was fixed with b324a14.

**Comment by sorenbryder** [comment]
No need to be sorry. Just wanted to let you know :)
