### ISSUE TITLE
[BUG] Uppercase namespace issue

### ISSUE THREAD

**Issue by romm** [pagemachine/cors#5]
I was having the message `No class named PAGEmachine\CORS\Hooks\ContentPostProcessorHook` on every frontend page.

Changing every namespace declaration and call by `CORS` → `Cors` resolved this.

FYI, the file `typo3temp/Cache/Data/cache_classes/pagemachine_cors_hooks_contentpostprocessorhook` is empty when the namespace is `CORS`.

**Comment by ffrewer** [comment]
Haven't got the message with T3 v6.2.15 - but it didn't work 
I can confirm that the solution works. Thanks.

**Comment by mbrodala** [comment]
I think I can confirm this. The old TYPO3 class loader as used in 6.2 turns the `CORS` within the FQCN into the extension name `c_o_r_s` (using `GeneralUtility::camelCaseToLowerCaseUnderscored()`) and thus fails to find the class files. I'll change the namespace and upload a fixed version.

**Comment by mbrodala** [comment]
I have just released version 1.2.13 which will show up on TER soon. Please update to that version and let me know if everything works now.

**Comment by ffrewer** [comment]
FYI, https://wiki.typo3.org/Namespaces:

```
"The second part of the namespace (in case of core classes the third part) is treated as the
extension key. Pick an extension key to your liking, thanks to the unique vendor name collisions 
with other extensions will not happen. The extension key part in the namespace have to be 
written in UpperCamelCase and is internally transformed to lowercase_underscore."
```

**Comment by mbrodala** [comment]
Yeah, forgot about this since I exclusively use Composer these days. ;-)
